//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Animal1 = new HashSet<Animal>();
            this.Animal11 = new HashSet<Animal>();
            this.CharacteristicsScores = new HashSet<CharacteristicsScore>();
            this.DairyProductivities = new HashSet<DairyProductivity>();
            this.Healths = new HashSet<Health>();
            this.ImunizationRecords = new HashSet<ImunizationRecord>();
        }
    
        public int animalId { get; set; }
        public string species { get; set; }
        public string breed { get; set; }
        public System.DateTime birthDate { get; set; }
        public string gender { get; set; }
        public int birthWeight { get; set; }
        public string hornType { get; set; }
        public string PatternDiscription { get; set; }
        public string earType { get; set; }
        public int CurrentWeight { get; set; }
        public string famachaScore { get; set; }
        public string numFreshenings { get; set; }
        public string registrationNumber { get; set; }
        public string rFIDNumber { get; set; }
        public string TagNumber { get; set; }
        public string scrapieNumber { get; set; }
        public string leftEarTatoo { get; set; }
        public string rightEarTatoo { get; set; }
        public string animalName { get; set; }
        public int fatherId { get; set; }
        public int motherId { get; set; }
        public bool isDeceased { get; set; }
        public int farmId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal1 { get; set; }
        public virtual Animal Animal2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal11 { get; set; }
        public virtual Animal Animal3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacteristicsScore> CharacteristicsScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DairyProductivity> DairyProductivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Health> Healths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImunizationRecord> ImunizationRecords { get; set; }
        public virtual Farm Farm { get; set; }
    }
}
