//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacteristicsScore
    {
        public int characteristicsId { get; set; }
        public int animalId { get; set; }
        public int strength { get; set; }
        public int stature { get; set; }
        public int Capacity { get; set; }
        public int dairyness { get; set; }
        public int rumpAngle { get; set; }
        public int rumpWidth { get; set; }
        public int rearLegAngulation { get; set; }
        public int foreLegAngulation { get; set; }
        public int foreLegAttachment { get; set; }
        public int EscutionArch { get; set; }
        public int EscutionHeight { get; set; }
        public int medialSuspendoryLigament { get; set; }
        public int uderDepth { get; set; }
        public int teatPlacement { get; set; }
        public int teatDiameter { get; set; }
        public int Head { get; set; }
        public int ShoulderAssembly { get; set; }
        public int LegsFront { get; set; }
        public int LegsRear { get; set; }
        public int Feet { get; set; }
        public int Pastern { get; set; }
        public int Back { get; set; }
        public int UdderTexture { get; set; }
        public string Remarks { get; set; }
        public string Defects { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
