//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Health()
        {
            this.TestRecords = new HashSet<TestRecord>();
        }
    
        public int healthId { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public string condition { get; set; }
        public string symptoms { get; set; }
        public Nullable<int> occurances { get; set; }
        public string treatment { get; set; }
        public Nullable<int> ImunizationId { get; set; }
    
        public virtual Animal Animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRecord> TestRecords { get; set; }
        public virtual ImunizationRecord ImunizationRecord { get; set; }
    }
}
