//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.ImunizationRecords = new HashSet<ImunizationRecord>();
        }
    
        public int medicineId { get; set; }
        public string medicineName { get; set; }
        public string recomendedUsages { get; set; }
        public string recomendedDosage { get; set; }
        public string recomendedMethodDelivery { get; set; }
        public string amountAvailable { get; set; }
        public System.DateTime expirationDate { get; set; }
        public string sideEfects { get; set; }
        public int farmId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImunizationRecord> ImunizationRecords { get; set; }
        public virtual Farm Farm { get; set; }
    }
}
