//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRecord
    {
        public int testId { get; set; }
        public string testName { get; set; }
        public string testType { get; set; }
        public string ImportantInfo { get; set; }
        public string TestResults { get; set; }
        public int healthId { get; set; }
    
        public virtual Health Health { get; set; }
    }
}
